version: '3'

services:
  api:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    restart: "no"
    expose:
      - 8000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - ENVIRONMENT=${ENVIRONMENT-production}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - SENTRY_DSN_KEY
      - API_SUPERUSER_PASSWORD=${API_SUPERUSER_PASSWORD}
      - API_SUPERUSER_TOKEN=${API_SUPERUSER_TOKEN}
      - API_BASE_URL=${API_BASE_URL}
      - API_INTERNAL_BASE_URL=${API_INTERNAL_BASE_URL}
      - EMAIL_NOREPLY_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_REGION_NAME
      - ERRBIT_URL
      - ERRBIT_KEY
    healthcheck:
      test: "curl --silent --fail http://localhost:8000/version/ || exit 1"
  nginx:
    image: booora/nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /static:/static
  celery:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "CELERY_WORKER_NAME=default ./start_celery_worker.sh -P prefork -Q default -c 2" ]
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "CELERY_WORKER_NAME=default ./ping_celery_worker.sh" ]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_indexing:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "CELERY_WORKER_NAME=indexing ./start_celery_worker.sh -P prefork -Q indexing -c 2" ]
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "CELERY_WORKER_NAME=indexing ./ping_celery_worker.sh" ]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_concurrent:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "CELERY_WORKER_NAME=concurrent ./start_celery_worker.sh -P prefork -Q concurrent -c 2" ]
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "CELERY_WORKER_NAME=concurrent ./ping_celery_worker.sh" ]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_bulk_import_0_1:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "CELERY_WORKER_NAME=bulk_import_0_1 ./start_celery_worker.sh -Q bulk_import_0,bulk_import_1 -c 1" ]
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "CELERY_WORKER_NAME=bulk_import_0_1 ./ping_celery_worker.sh" ]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_bulk_import_2_3:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "CELERY_WORKER_NAME=bulk_import_2_3 ./start_celery_worker.sh -Q bulk_import_2,bulk_import_3 -c 1" ]
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "CELERY_WORKER_NAME=bulk_import_2_3 ./ping_celery_worker.sh" ]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  celery_bulk_import_root:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "CELERY_WORKER_NAME=bulk_import_root ./start_celery_worker.sh -Q bulk_import_root -c 1" ]
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "CELERY_WORKER_NAME=bulk_import_root ./ping_celery_worker.sh" ]
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEBUG=${DEBUG-FALSE}
      - ERRBIT_URL
      - ERRBIT_KEY
  flower:
    image: openconceptlab/oclapi2:${ENVIRONMENT-production}
    command: [ "bash", "-c", "./start_flower.sh" ]
    ports:
      - 5555:5555
    environment:
      - FLOWER_USER=${FLOWER_USER}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

    healthcheck:
      test: "curl --silent --fail -u $${FLOWER_USER:-root}:$${FLOWER_PASSWORD:-Root123} http://0.0.0.0:5555/metrics || exit 1"
  es:
    image: elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: "no"
    healthcheck:
      test: "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
volumes:
  es-data:
