- name: Playbook to deploy open concept lab api
  hosts:
  gather_facts: false
  tasks:
    - name: Update apt packages
      remote_user: ubuntu
      apt:
        update_cache: yes

    - name: Add remote 'ubuntu' user to 'docker' group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: Clone git repo
      git:
        url: https://github.com/booorayan/oclapi2.git
        dest: /home/ubuntu

    - name: Update vm c=map count for project
      command: sudo sysctl vm.map_count=266

    - name: Run docker-compose file