- name: Playbook to deploy open concept lab api
  hosts: ec2
  gather_facts: false
  remote_user: ubuntu
  become: yes

  tasks:

    - name: Install docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent
        - python3-pip
        - python3-setuptools

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

#    - name: Verify that we have the key with the fingerprint
#      apt_key:
#        id: 0EBFCD88
#        state: present

    - name: Set up stable repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

#    - name: Install docker
#      apt:
#        name: docker-ce
#        state: present
#        update_cache: yes

    - name: Add user 'ubuntu' to 'docker' group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Update vm.max_map_count for project
      command: sysctl -w vm.max_map_count=262144

    - name: Copy Docker compose file to run containers
      copy:
        src: ../docker-compose.prod.yml
        dest: /home/ubuntu

    - name: Rename compose file
      command: mv /home/ubuntu/docker-compose.prod.yml /home/ubuntu/docker-compose.yml

    - name: Copy env file to host
      copy:
        src: ../.env
        dest: /home/ubuntu

#    - name: Spin up docker containers for the api, celery, es and flower
#      docker_compose:
#        files: ../docker-compose.prod.yml
#
#      register: output

    - name: Run container with docker compose
      command: docker-compose up

      register: output

    - name: Debug
      debug:
        var: output

